pull_request_rules:
  - name: Add needs-dco label when DCO check failed
    conditions:
      - or:
          - base=main
          - base~=^2(\.\d+){1,2}$
      - -status-success=DCO
    actions:
      label:
        remove:
          - dco-passed
        add:
          - needs-dco

  - name: Add dco-passed label when DCO check passed
    conditions:
      - or:
          - base=main
          - base~=^2(\.\d+){1,2}$
      - status-success=DCO
    actions:
      label:
        remove:
          - needs-dco
        add:
          - dco-passed

  - name: Test passed for code changed
    conditions:
      - or:
          - base=main
          - base~=^2(\.\d+){1,2}$
      - 'status-success=Lint and Test / Run Lint and Tests (3.9) (pull_request) '
    actions:
      label:
        add:
          - ci-passed

  - name: Remove ci-passed label when test failed
    conditions:
      - or:
        - base=main
        - base~=^2(\.\d+){1,2}$
      - or:
        - 'status-success=Lint and Test / Run Lint and Tests (3.9) (pull_request) '
    actions:
      label:
        remove:
          - ci-passed

